apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
        - name: url
          image: dragoon920/url
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: url-srv
spec:
  type: NodePort
  selector:
    app: url
  ports:
    - name: url
      protocol: TCP
      port: 3001
      targetPort: 3001
